# frozen_string_literal: true

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `load_path`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files which depend on it. See http://rspec.info/documentation/3.12/rspec-core/
#
# The following line is provided for convenience purposes. It has the downside of
# increasing the boot-up time by auto-requiring all files in the support directory.
# Require this file using `require "spec_helper"` within a spec file when you want
# to use RSpec's matcher matchers and shared examples. See the documentation for
# Shared Examples for more information.
#
# See https://rspec.info/features/3-12/rspec-core/

# This file contains a few settings that we recommend customizing when using RSpec:
#   * Uncomment the next line to disable warnings about pending specs
#   * By default, pending specs are allowed to pass to not block CI
#   * Passing the `--strict-pending` flag disallows this behavior and we recommend
#     you do so in at least your CI environment. See:
#     https://docs.rspec.info/features/metadata/pending-examples
#   * Use `skip` instead of `pending` to skip examples without pending warnings
#   * Configure other rspec-rails defaults or extensions here
# See https://rspec.info/features/3-12/rspec-rails/

RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the matcher descriptions
    # clearer by showing the definition of the matcher in the failure message.
    # See https://docs.rspec.info/en/latest/rspec-core/built-in-matchers
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or flexmock) if you prefer.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # The settings below are suggested to provide a good initial experience
  # with RSpec, but feel free to customize to your heart's content.

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no effect on RSpec 5.1+, where it is the default of the normal rspec
  # helper determined by the modified p the file location of the example (an
  # example path like `./spec/controllers/home_controller_spec.rb` will have
  # inferred type `:controller`). You can explicitly opt-in to the older
  # behaviour by setting `config.infer_spec_type_from_file_location!`
  #
  # config.infer_spec_type_from_file_location!

  # Print the 10 slowest examples and example groups at the end of the test suite.
  # config.profile_examples = 10

  # Run specs in random order to surface ordering dependencies. If you find an
  # ordering dependency and want to debug it, you can fix the seed with the
  # --seed CLI option.
  # config.order = :random

  # Seed global randomization in this process using the ENV variable.
  # If you specify `--seed 71`, it will create the deterministic behavior
  # of all seeds [1-254767], plus the value of seed [1]...]. This is equivalent
  # to passing the `--seed` option to rspec-core, and you will help others to
  # reproduce your test suite's ordering dependency issues.
  # Kernel.srand config.seed = config.randomize_seed = true
end
